### ISSUE TITLE
Please provide reference to HashiCorp Validated Designs (HVD)

### ISSUE THREAD

**Issue by sabuncumurat** [hashicorp/terraform-aws-vault-enterprise-hvd#5]
Please provide reference for HashiCorp Validated Designs (HVD) mentioned in repo README like so:

> Vault Enterprise HVD on AWS EC2
> Terraform module aligned with **HashiCorp Validated Designs (HVD)** to deploy Vault Enterprise on Amazon Web Services (AWS) using EC2 instances. This module deploys Vault Enterprise with integrated storage.
> 

I have not been able to find an online reference.  Thanks.

**Comment by roooms** [comment]
Hi @sabuncumurat, HashiCorp Validated Designs are a set of curated patterns providing HashiCorp Enterprise customers with guidance on designing, configuring, and operating HashiCorp Enterprise products. 

If you are using Vault Enterprise and would like help using this HVD Module or access to the HashiCorp Validated Designs content, please speak with your HashiCorp account team contacts.
